const { pool } = require('../config/db');

const obterIp = (req) => req.headers['x-forwarded-for'] || req.socket?.remoteAddress || null;

const gravarLogAcesso = async (utilizadorId, nome) => {
    try {
        // A coluna id é GENERATED BY DEFAULT AS IDENTITY: deixamos a BD gerá-la
        // (evita a race condition de calcular MAX(id)+1 manualmente).
        await pool.query(
            'INSERT INTO logs_acesso (utilizador_id, data_hora_acesso) VALUES ($1, NOW())',
            [utilizadorId]
        );
        console.log(`✅ LOGIN GRAVADO NA BD: O utilizador ${nome} entrou na plataforma!`);
    } catch (erroAcesso) {
        console.error(`❌ ERRO AO GRAVAR ACESSO de ${nome}:`, erroAcesso.message);
    }
};

const gravarLogSeguranca = async (tipo, email, utilizadorId, ip) => {
    try {
        await pool.query(
            'INSERT INTO logs_seguranca (tipo, email, utilizador_id, ip) VALUES ($1, $2, $3, $4)',
            [tipo, email || null, utilizadorId || null, ip || null]
        );
    } catch (err) {
        console.error('❌ Erro ao gravar log de segurança:', err.message);
    }
};

module.exports = { obterIp, gravarLogAcesso, gravarLogSeguranca };
