-- ============================================================
-- CyberLearn — Esquema da base de dados (PostgreSQL)
-- ------------------------------------------------------------
-- ⚠️ Reconstruído a partir do código do servidor. A BD de produção
-- foi criada manualmente; valida este ficheiro contra ela com:
--   pg_dump "$DATABASE_URL" --schema-only --no-owner > schema_prod.sql
-- e ajusta as diferenças. Para criar uma BD nova de raiz:
--   psql "$DATABASE_URL" -f schema.sql
-- Depois aplica as migrações em db/migrations/ por ordem.
-- ============================================================

-- ---------- Utilizadores (aluno / professor / admin) ----------
CREATE TABLE IF NOT EXISTS utilizadores (
    id                      SERIAL PRIMARY KEY,
    nome                    VARCHAR(255) NOT NULL,
    email                   VARCHAR(255) NOT NULL UNIQUE,
    password_hash           VARCHAR(255) NOT NULL,
    perfil                  VARCHAR(50)  NOT NULL,          -- 'aluno' | 'professor' | 'admin'
    ativo                   BOOLEAN      NOT NULL DEFAULT true,
    data_registo            TIMESTAMP    DEFAULT NOW(),
    -- Perfil público
    avatar                  TEXT,
    biografia               TEXT,
    biografia_prof          TEXT,
    metodologia             TEXT,
    nivel_experiencia       VARCHAR(100),
    area_interesse          VARCHAR(255),
    conquistas              TEXT,
    github                  VARCHAR(255),
    linkedin                VARCHAR(255),
    -- Gamificação
    xp_total                INTEGER      DEFAULT 0,
    last_login_date         DATE,
    streak_count            INTEGER      DEFAULT 0,
    -- 2FA por email e recuperação de senha
    codigo_email_2fa        VARCHAR(6),
    codigo_email_expiracao  TIMESTAMP,
    codigo_2fa_tentativas   INTEGER      NOT NULL DEFAULT 0,
    reset_token             VARCHAR(6),
    reset_token_expiry      TIMESTAMP
);

-- ---------- Cursos ----------
CREATE TABLE IF NOT EXISTS cursos (
    id             SERIAL PRIMARY KEY,
    titulo         VARCHAR(255) NOT NULL,
    nivel          VARCHAR(100),
    descricao      TEXT,
    conteudo_licao TEXT,
    professor_id   INTEGER REFERENCES utilizadores(id) ON DELETE CASCADE,
    aprovado       BOOLEAN NOT NULL DEFAULT false,
    data_criacao   TIMESTAMP DEFAULT NOW()
);

-- ---------- Quizzes (uma linha = uma pergunta; agrupadas por titulo) ----------
CREATE TABLE IF NOT EXISTS quizzes (
    id               SERIAL PRIMARY KEY,
    titulo           VARCHAR(255) NOT NULL,
    curso_id         INTEGER REFERENCES cursos(id) ON DELETE CASCADE,
    pergunta         TEXT NOT NULL,
    opcao_a          TEXT,
    opcao_b          TEXT,
    opcao_c          TEXT,
    opcao_d          TEXT,
    resposta_correta VARCHAR(1),                            -- 'a' | 'b' | 'c' | 'd'
    aprovado         BOOLEAN NOT NULL DEFAULT false
);

-- ---------- Tentativas de quizzes (resultados dos alunos) ----------
CREATE TABLE IF NOT EXISTS tentativas_quizzes (
    id              SERIAL PRIMARY KEY,
    utilizador_id   INTEGER REFERENCES utilizadores(id) ON DELETE CASCADE,
    quiz_titulo     VARCHAR(255),
    acertos         INTEGER NOT NULL DEFAULT 0,
    total_perguntas INTEGER NOT NULL DEFAULT 0,
    data_realizacao TIMESTAMP DEFAULT NOW()
);

-- ---------- Resultados de quizzes (legado; apenas limpo em cascata) ----------
CREATE TABLE IF NOT EXISTS resultados_quizzes (
    id            SERIAL PRIMARY KEY,
    utilizador_id INTEGER REFERENCES utilizadores(id) ON DELETE CASCADE
);

-- ---------- Gamificação: catálogo de conquistas e atribuições ----------
CREATE TABLE IF NOT EXISTS conquistas_catalogo (
    id        SERIAL PRIMARY KEY,
    nome      VARCHAR(255) NOT NULL UNIQUE,
    descricao TEXT,
    icone     VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS utilizador_conquistas (
    utilizador_id INTEGER REFERENCES utilizadores(id) ON DELETE CASCADE,
    conquista_id  INTEGER REFERENCES conquistas_catalogo(id) ON DELETE CASCADE,
    data_obtencao TIMESTAMP DEFAULT NOW(),
    -- O ON CONFLICT DO NOTHING do código depende desta unicidade.
    PRIMARY KEY (utilizador_id, conquista_id)
);

-- ---------- Logs ----------
CREATE TABLE IF NOT EXISTS logs_acesso (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilizador_id    INTEGER REFERENCES utilizadores(id) ON DELETE CASCADE,
    data_hora_acesso TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS logs_seguranca (
    id            SERIAL PRIMARY KEY,
    tipo          VARCHAR(50),                              -- 'login_falha' | '2fa_falha' | 'login_sucesso'
    email         VARCHAR(255),
    utilizador_id INTEGER,
    ip            VARCHAR(100),
    data_criacao  TIMESTAMP DEFAULT NOW()
);

-- ---------- Comentários nas lições ----------
CREATE TABLE IF NOT EXISTS comentarios_licao (
    id              SERIAL PRIMARY KEY,
    curso_id        INTEGER REFERENCES cursos(id) ON DELETE CASCADE,
    utilizador_id   INTEGER REFERENCES utilizadores(id) ON DELETE CASCADE,
    nome_utilizador VARCHAR(255),
    comentario      TEXT,
    data_criacao    TIMESTAMP DEFAULT NOW()
);

-- ---------- Notificações persistentes ----------
CREATE TABLE IF NOT EXISTS notificacoes_sistema (
    id            SERIAL PRIMARY KEY,
    utilizador_id INTEGER NULL,
    perfil_alvo   VARCHAR(50) NULL,
    icone         VARCHAR(50),
    cor           VARCHAR(50),
    titulo        VARCHAR(255),
    mensagem      TEXT,
    acao          VARCHAR(255),
    data_criacao  TIMESTAMP DEFAULT NOW()
);

-- ---------- Índices para as queries mais frequentes ----------
CREATE INDEX IF NOT EXISTS idx_cursos_professor        ON cursos (professor_id);
CREATE INDEX IF NOT EXISTS idx_quizzes_curso           ON quizzes (curso_id);
CREATE INDEX IF NOT EXISTS idx_tentativas_utilizador   ON tentativas_quizzes (utilizador_id);
CREATE INDEX IF NOT EXISTS idx_logs_acesso_utilizador  ON logs_acesso (utilizador_id);
CREATE INDEX IF NOT EXISTS idx_notificacoes_alvo       ON notificacoes_sistema (utilizador_id, perfil_alvo);
